services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_URSR}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init_script/init.sql:/docker-entrypoint-initdb.d/init.sql

  neo4j:
    image: neo4j:5
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - ./data/neo4j:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]

  # qdrant:
  #   image: qdrant/qdrant:v1.15
  #   restart: always
  #   volumes:
  #   - ./data/qdrant:/qdrant/storage:z
  #   ports:
  #   - "6333:6333"
  #   - "6334:6334"
